---
title: "CarterMeseck"
author: "Carter Meseck"
date: "4/26/2021"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(readr)
library(readxl)
library(dplyr)
library(devtools)
```
```{r}
data <- read.csv("healthcare-dataset-stroke-data.csv")
head(data)


```
```{r}
## Finding Average Person vs Average Person who has had a stroke.
newData <- data[(data$bmi != 'N/A'),]

summary(data)
table(data$gender)
table(data$Residence_type)
table(data$ever_married)
table(data$work_type)
table(data$smoking_status)


## Average Person is 43(.23) years old.
## Average Person has 5% chance to have heart disease
## Average Person has 28.89 BMI
## Average Person has 106.15 Glucose level
## Average Person has 9.7% chance to have hypertension
## Average person is a female
## Average person has never smoked or unknown
## Average person has a 4.9% chance to have had a stroke.
## Average person lives in an urban residence
## Average person is privately employed
## Average person has been married

sd(data$age)
sd(data$heart_disease)
sd(newData$bmi)
sd(data$avg_glucose_level)
sd(data$hypertension)
sd(data$stroke)


## Standard Deviation:
# Age: 22.61
# Heart Disease: .226
# BMI: 7.85
# Glucose: 45.28
# Hypertension: 0.30
# Stroke: 0.22

strokes <- data[which(data$stroke == 1 & data$bmi != 'N/A'), ]

summary(strokes)
table(strokes$gender)
table(strokes$Residence_type)
table(strokes$ever_married)
table(strokes$work_type)
table(strokes$smoking_status)

## Average Stroker is 67(.71) years old.
## Average Stroker has 19.1% chance to have heart disease
## Average Stroker has 30.5 BMI
## Average Stroker has 134.6 Glucose level
## Average Stroker has 28.7% chance to have hypertension
## Average Stroker is a female (However the average person from our dataset was a female so not surprising)
## Average Stroker has never smoked, second place being formerly smoked as opposed to unknown in non smokers.
## Average Stroker has a 100% chance to have had a stroke.
## Average Stroker lives in an urban residence, however the difference is only 9 so I wouldn't say this is statistically significant.
## Average Stroker is privately employed
## Average Stroker has been married

sd(strokes$age)
sd(strokes$heart_disease)
sd(strokes$bmi)
sd(strokes$avg_glucose_level)
sd(strokes$hypertension)
sd(strokes$stroke)


## Standard Deviation:
# Age: 12.4
# Heart Disease: 0.39
# BMI: 6.33
# Glucose: 62.46
# Hypertension: 0.45

# For Strokers, the Standard Deviation for age seems to be much lower. It would seem then, that strokers are all around a close age.

```


### Average age of each smoking status


```{r}


## Find average age of people by smoke group.
smoke <- newData[newData$smoking_status == "smokes" | newData$smoking_status == "formerly smoked", ]

summary(smoke)

noSmoke <- newData[newData$smoking_status == "never smoked", ]

summary(noSmoke)


## Average age of someone who has smoked or smoked in the past is 51.24
## Average age of someone who hasn't smoked is 46.74
## There is about an average increase of 2% in chance that someone who smoked will have had a stroke.
## Almost double chance of someone to have heart disease that smokes vs non smoke
## 40.6% more likely for a smoker to have a stroke vs non smoker.

<<<<<<< HEAD
data %>% group_by(smoking_status) %>%
  mutate(age_avg = mean(age)) %>%
  ggplot(aes(x = `smoking_status`, y=`age_avg`, fill = `smoking_status`)) + geom_bar(stat="identity", position = "dodge") + 
     ggtitle("Percentage of Strokes in Relation to Smoking Status")
=======
sd(smoke$age)
sd(smoke$heart_disease)
sd(smoke$bmi)
sd(smoke$avg_glucose_level)
sd(smoke$hypertension)
sd(smoke$stroke)

## Standard Deviation:
# Age: 17.51
# Heart Disease: 0.28
# BMI: 7.08
# Glucose: 49.23
# Hypertension: 0.33
# Stroke: 0.24

sd(noSmoke$age)
sd(noSmoke$heart_disease)
sd(noSmoke$bmi)
sd(noSmoke$avg_glucose_level)
sd(noSmoke$hypertension)
sd(noSmoke$stroke)

## Standard Deviation:
# Age: 19.71
# Heart Disease: 0.20
# BMI: 7.46
# Glucose: 46.34
# Hypertension: 0.32
# Stroke: 0.21
>>>>>>> 3ccb24df17af9b6ab6b5bd7cbe65f1bb44d8d724


```
```{r}
## Looking into female vs male to see if there are any discrepancies there.
table(strokes$gender)
## 120 Females have had a stroke and 89 Males have. Proportion is 1.35
table(data$gender)
## 2994 Females and 2115 Males in the dataset. Proportion is 1.42

## Proportion of females to males is lower in people that have had a stroke, but not significant enough to extract any  meaning.

male <- newData[newData$gender == "Male", ]
female <- newData[newData$gender == "Female",]

summary(male)
table(male$ever_married)
table(male$work_type)
table(male$smoking_status)
# 5% chance for Male to have a stroke
# Avg male age for dataset is 42.5
# Avg Male hypertension is 10.5%
# Avg Male Heart disease 7.8%
# Avg Male glucose level is 109
# 56.4% Chance for Male to not have been married
# 55.3% Chance for Male to work Private
# 47.1% Chance for Male to never have smoked

sd(male$age)
sd(male$heart_disease)
sd(male$bmi)
sd(male$avg_glucose_level)
sd(male$hypertension)
sd(male$stroke)

## Standard Deviation:
# Age: 23.48
# Heart Disease: 0.26
# BMI: 7.46
# Glucose: 46.50
# Hypertension: 0.30
# Stroke: 0.21


summary(female)
table(female$ever_married)
table(female$work_type)
table(female$smoking_status)

# 4.7% chance for Female to have a stroke
# Avg Female age for dataset is 43.8
# Avg Female hypertension is 9.2%
# Avg Female Heart disease 3.8%
# Avg Female glucose level is 104.1
# 49.6% Chance for Female to not have been married
# 58.6% Chance for Female to work Private
# 57% Chance for Female to never have smoked

<<<<<<< HEAD
=======
sd(female$age)
sd(female$heart_disease)
sd(female$bmi)
sd(female$avg_glucose_level)
sd(female$hypertension)
sd(female$stroke)

## Standard Deviation:
# Age: 21.88
# Heart Disease: 0.18
# BMI: 8.11
# Glucose:
# Hypertension: 0.28
# Stroke: 0.20


>>>>>>> 3ccb24df17af9b6ab6b5bd7cbe65f1bb44d8d724
# From this we can tell that in this dataset, females are much less likely to have heart disease, have been married, and have smoked.

```
```{r}

data %>% filter(gender != "Other") %>% group_by(`gender`,smoking_status,heart_disease) %>% 
  mutate(stroke_avg = sum(stroke)/n()) %>%
  
  ggplot(aes(x = `gender`, y=`stroke_avg`, fill = `smoking_status`)) + geom_bar(stat="identity", position = "dodge") + 
  
    facet_grid(rows = (data %>% filter(gender != "Other"))$heart_disease, labeller = as_labeller(c("0"="Heart Disease", "1"="No Heart Disease"))) + 
    
    ggtitle("Percentage of Strokes in Relation to Gender, Smoking Status, and Heart Disease") + 
    xlab("Gender") + ylab("Stroke Risk")  +
    scale_y_continuous(labels = scales::percent) +
    scale_fill_discrete(name="Smoking Status", labels=c("Former Smoker", "Never Smoked", "Smokes", "Unknown"))

```










