---
title: "Final Project Proposal"
author: "Felix Baez, Carter Meseck, Austin Nebel, Ryan Herren and Chris Anderson"
output: html_document
---

The team will submit the link to their team final project GitHub repo. The repo should include a proposal.Rmd file, which contains the following items:

## 1. The names of team members & project coordinator

Felix Baez, Carter Meseck, Austin Nebel, Ryan Herren and Chris Anderson

## 2. The link to the data source

https://www.kaggle.com/fedesoriano/stroke-prediction-dataset

## 3. An overview of the dataset

This dataset contains information for different factors that may be related to strokes. Strokes are believed to cause around 11% of total deaths. This dataset is used to predict whether a patient is likely to get stroke based on the variables like gender, age, various diseases, and smoking status. Each row in the data provides relavant information about the patient. The variables are listed below: 

- 1: id: unique identifier
- 2: gender: "Male", "Female" or "Other"
- 3: age: age of the patient
- 4: hypertension: 0 if the patient doesn't have hypertension, 1 if the patient has hypertension
- 5: heart_disease: 0 if the patient doesn't have any heart diseases, 1 if the patient has a heart disease
- 6: ever_married: "No" or "Yes"
- 7: work_type: "children", "Govt_jov", "Never_worked", "Private" or "Self-employed"
- 8: Residence_type: "Rural" or "Urban"
- 9: avg_glucose_level: average glucose level in blood
- 10: bmi: body mass index
- 11: smoking_status: "formerly smoked", "never smoked", "smokes" or "Unknown"*
- 12: stroke: 1 if the patient had a stroke or 0 if not
*Note: "Unknown" in smoking_status means that the information is unavailable for this patient
    
    
## 4. A brief plan for an exploratory analysis: What questions can be answered from the dataset?
We can answer many questions based on these variables but here are four that can help:
- 1: What factor is the largest indicator of stroke for each age group?
- 2: How does chance of stroke change with age for each employment category?
- 3: Does heart disease increase chance of stroke?
- 4: How does chance of stroke change with age?
- 5: Does smoking increase chances of stroke?

*As we work more on the final project, we will come up with more and improved questions.

```{r}
library(readr) 
df <- read_csv("healthcare-dataset-stroke-data.csv") 
head(df)
